
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import store from "../app/redux/store"; // Import your store
// import { Provider } from "react-redux"; 
import { Toaster } from "react-hot-toast";
import ReduxProvider from "./redux/ReduxProvider";
import LoadUser from "./redux/LoadUser";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "MedGuardian - Smart Medication Reminder & Health Tracker App",
  description: "MediTracker is an advanced medication reminder app that helps you track and manage your daily medicine intake. Get real-time alerts, dose history, and missed dose tracking—all in one place! Stay healthy with the best medicine tracker app today!",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       
         <ReduxProvider store={store}>
         <LoadUser />

          {children}
          <Toaster />
        </ReduxProvider>
      </body>
    </html>
  );
}

// **
// 'use client'

// import { Geist, Geist_Mono } from "next/font/google";
// import { Provider } from "react-redux"; // Import the Provider
// import store from "../app/redux/store"; // Import your store
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {/* Wrap the app with the Provider */}
//         <Provider store={store}>
//           {children}
//         </Provider>
//       </body>
//     </html>
//   );
// }
